"""Simplify models: Remove Game, update GameState

Revision ID: d9b28fa5412c
Revises: e97d4f677024
Create Date: 2025-01-05 12:44:36.190580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b28fa5412c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_word', sa.String(length=50), nullable=False),
    sa.Column('display_word', sa.String(length=50), nullable=False),
    sa.Column('mistake_count', sa.Integer(), nullable=True),
    sa.Column('wrong_letters', sa.String(length=255), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('coins', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('game')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('winstreak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('highscore', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('highscore')
        batch_op.drop_column('winstreak')
        batch_op.drop_column('coins')

    op.create_table('game',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('word', sa.VARCHAR(length=50), nullable=False),
    sa.Column('mistake_count', sa.INTEGER(), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('game_state')
    # ### end Alembic commands ###
